{{- if and .Values.enabled (not .Values.auth.existingSecretName) .Values.auth.secretKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "label-studio.fullname" . }}-auth
  labels:
    {{- include "label-studio.labels" . | nindent 4 }}
    app.kubernetes.io/component: labelstudio
type: Opaque
stringData:
  SECRET_KEY: {{ .Values.auth.secretKey | quote }}
{{- end }}
